### ISSUE TITLE
Multiple Images with same Content

### ISSUE THREAD

**Issue by cytec** [opennota/screengen#3]
Hi,

I just found something strange:

1. when the interval in which images are taken from the video is to low (2 seconds in my test) i got several images showing the exact same content.
2. it seems like the interval doesn't really skip to the correct movie position at all... for example: i get an image which (according to screengen) is from `00:04:15` but when i open the movie in VLC... the timestamp shows `00:04:00` so i've tried again with another movie and got an image at position `00:01:46` but in VLC it's at `00:01:35` 

any guess why this happens?

EDIT: first movie i've mentioned is BigBuckBunny... 
also i checked if it may be an error caused by me, but it also happens with `vcut` as well

**Comment by opennota** [comment]
Have you tried to get screenshots using ffmpeg command-line utility?

1. Specifying the timestamp as an input optiion (before -i).

```
ffmpeg -ss 00:04:15 -i movie.mp4 -vframes 1 out1.jpg
```

2. Specifying the timestamp as an output optiion (after -i).

```
ffmpeg -i movie.mp4 -ss 00:04:15 -vframes 1 out2.jpg
```

What are the results?

**Comment by cytec** [comment]
yup both return the correct image... but the 2nd command needs much more time. (43.865s) the first one just takes (1.418s)

here are the images:

`1. ffmpeg`
![out1](https://cloud.githubusercontent.com/assets/1104903/9383774/c6916104-474b-11e5-8e96-40889906c88e.jpg)

`2. ffmpeg`
![out2](https://cloud.githubusercontent.com/assets/1104903/9383782/d3e410cc-474b-11e5-9119-e6c32ee8b28a.jpg)

`screengen`
![big_buck_bunny_720p_stereo-03](https://cloud.githubusercontent.com/assets/1104903/9383794/de606ece-474b-11e5-80d9-6219213cbd7b.jpg)

**Comment by opennota** [comment]
`avformat_seek_file` is inaccurate, by design or due to a bug (or both). ffmpeg does some smart calculations and reads a number of frames instead of a single frame. I did something simpler and now the images are close enough to the images generated by ffmpeg. Check if your problem is solved by this.

**Comment by opennota** [comment]
As for the images with the same content, it can be hard to get different images if the interval is less than the distance between key frames.

**Comment by cytec** [comment]
Nice!
now im getting the correct image and the duplicate image creation is also fixed!
Thanks alot
