### ISSUE TITLE
broken with ffmpeg 3.x

### ISSUE THREAD

**Issue by mutschler** [opennota/screengen#7]
screengen isn't compatible with ffmpeg 3.x atm, as far as i can see there are two changes in ffmpeg's libraries which break compiling for screengen:

1. https://github.com/opennota/screengen/blob/master/screengen.go#L196 isn't needed anymore as `priv` is deprecated/gone in 3.x see: https://www.ffmpeg.org/doxygen/3.0/structAVPacket.html
2. https://github.com/opennota/screengen/blob/master/screengen.go#L216 `PIX_FMT_RGBA` has been deprecated/renamed to for a while is now gone, use  `AV_PIX_FMT_RGBA` see: https://www.ffmpeg.org/doxygen/3.0/pixfmt_8h.html  

the second one should be an easy fix as its already `PIX_FMT_RGBA` is already just an alternative name for `AV_PIX_FMT_RGBA` in ffmpeg 2.5 if i remember correctly, for the first one there might be a check needed or something to provide compatibility with ffmpeg 2.x

**Comment by mutschler** [comment]
I've made a PR for the 2nd part here https://github.com/opennota/screengen/pull/8, not sure how to address the 1st problem

**Comment by opennota** [comment]
I've pushed a commit; check if it works for you.

**Comment by mutschler** [comment]
works like charm, thanks!
